- hosts: all
  become: yes
  remote_user: ansibleadm
  tasks:
  - name: Pull an Image "Sonatype/nexus3"
    docker_image:
      name: sonatype/nexus3
      source: pull
  - name: Create a Nexus container
    docker_container:
      name: Container_Nexus
      image: sonatype/nexus3
      ports:
      - 8081:8081
      state: started
  - name: check if container is running
    shell: docker ps
  - name: creata a nexus user
    set_fact:
      nexus_local_users:
        - username: my_user
          first_name: my
          last_name: user
          email: my@user.com
          password: "s3cr3t"
          roles:
            - developers
  - name: apply defaults to bower proxy repos
    set_fact:
      nexus_repos_maven_proxy:
        - name: central
          remote_url: 'https://repo1.maven.org/maven2/'
          layout_policy: permissive
  - name: apply defaults to bower proxy repos
    set_fact:
      nexus_repos_docker_proxy:
        - name: docker-proxy
          http_port: "{{ 5000 }}"   # need to specify the port number 
          v1_enabled: True
          index_type: "HUB"
          remote_url: "https://registry-1.docker.io"   # need to specify remote registry here
          use_nexus_certificates_to_access_index: false
  - name: apply defaults to bower proxy repos
    set_fact:
      nexus_repos_docker_hosted:
        - name: docker-hosted
          http_port: "{{ 5000 }}"  # need to specify the port number
          v1_enabled: True
      notify:
          - restart a specific container
      handlers:
        - name: restart a specific container
          systemd:
            name: Container_Nexus
            state: restarted
          when: nexus_service_state != 'stopped'
