---
#- hosts: all
#  become: true
#  vars:
#    container_count: 4
#    default_container_name: docker
#    default_container_image: ubuntu
#    default_container_command: sleep 1d

#  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
            #          - pip3
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      community.general.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create nexus containers
      community.general.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        ports:
        - 8081:8081
          # command: "{{ default_container_command }}"
        state: started
      with_sequence: count={{ container_count }}
    - name: check if container is running
      shell: docker ps
    - name: creata a nexus user
      set_fact:
        nexus_local_users:
        - username: my_user
          first_name: my
          last_name: user
          email: my@user.com
          password: "s3cr3t"
          roles:
          - developers



